### ISSUE TITLE
pthread_join NullPointerException

### ISSUE THREAD

**Issue by db7** [hernanponcedeleon/Dat3M#242]
This doesn't seem to work:

```c
#include <pthread.h>
void* run(void* arg) { return 0; }
int main() {
    pthread_t threads[1];
    pthread_create(&threads[0], 0, run, 0);
    pthread_join(threads[0], 0);}
    return 0;
}
```

I get this error:
```
1:44:26 [INFO] VisitorBoogie.visitLine_comment - SMACK version: 2.8.0 
Exception in thread "main" java.lang.NullPointerException
        at com.dat3m.dartagnan.parsers.program.boogie.PthreadPool.getCreatorFromPtr(PthreadPool.java:29)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.PthreadsProcedures.pthread_join(PthreadsProcedures.java:93)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.PthreadsProcedures.handlePthreadsFunctions(PthreadsProcedures.java:46)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitCall_cmd(VisitorBoogie.java:349)
        at com.dat3m.dartagnan.parsers.BoogieParser$Call_cmdContext.accept(BoogieParser.java:2752)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.dat3m.dartagnan.parsers.BoogieBaseVisitor.visitLabel_or_cmd(BoogieBaseVisitor.java:177)
        at com.dat3m.dartagnan.parsers.BoogieParser$Label_or_cmdContext.accept(BoogieParser.java:2129)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitProc_decl(VisitorBoogie.java:275)
        at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitMain(VisitorBoogie.java:132)
        at com.dat3m.dartagnan.parsers.BoogieParser$MainContext.accept(BoogieParser.java:235)
        at com.dat3m.dartagnan.parsers.program.ParserBoogie.parse(ParserBoogie.java:25)
        at com.dat3m.dartagnan.parsers.program.ProgramParser.parse(ProgramParser.java:33)
        at com.dat3m.dartagnan.parsers.program.ProgramParser.parse(ProgramParser.java:26)
        at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:83)
```

Is this supposed to be like that? Is there an issue on how `pthread_create/pthread_join` are handled?

**Comment by hernanponcedeleon** [comment]
We do have certain limitations due to the way we handle/model thread creating and joining. The main limitation is that `pthread_create` and `pthread_join` cannot be inside loops. I was not expecting defining an array of `pthread_t` would also cause problems but your example clearly shows it does. Therefore I would say that a second limitation is that each `pthread_t` variable must be explicitly defined, i.e. the following code works:
```
#include <pthread.h>
void* run(void* arg) { return NULL; }
int main() {
    pthread_t t0;
    pthread_create(&t0, 0, run, 0);
    pthread_join(t0, 0);
}
```
If you need more threads, e.g. 2, you need to use
```
#include <pthread.h>
void* run(void* arg) { return NULL; }
int main() {
    pthread_t t0, t1;
    pthread_create(&t0, 0, run, 0);
    pthread_create(&t1, 0, run, 0);
    pthread_join(t0, 0);
    pthread_join(t1, 0);
}
```
These limitations are currently not documented anywhere but I'll add them to the README.

**Comment by db7** [comment]
Ok, thanks for the clarification. I noticed that while manually unrolling a `pthread_create` loop.
