### ISSUE TITLE
ParsingException: __VERIFIER_nondet cannot be handled

### ISSUE THREAD

**Issue by fanhy2114** [hernanponcedeleon/Dat3M#37]
Hi.
I compile Dartagnan from your latest version of source code; then I use Dartagnan to check the validity of benchmarks from SV-COMP ConcurrentSafety category, however, benchmarks from |pthread-wmm| throw an exception like this:

Exception in thread "main" com.dat3m.dartagnan.parsers.program.utils.ParsingException: __VERIFIER_nondet cannot be handled
	at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitProc_decl(VisitorBoogie.java:297)
	at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitCall_cmd(VisitorBoogie.java:422)
	at com.dat3m.dartagnan.parsers.BoogieParser$Call_cmdContext.accept(BoogieParser.java:2698)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.dat3m.dartagnan.parsers.BoogieBaseVisitor.visitLabel_or_cmd(BoogieBaseVisitor.java:170)
	at com.dat3m.dartagnan.parsers.BoogieParser$Label_or_cmdContext.accept(BoogieParser.java:2075)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitProc_decl(VisitorBoogie.java:323)
	at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitCall_cmd(VisitorBoogie.java:422)
	at com.dat3m.dartagnan.parsers.BoogieParser$Call_cmdContext.accept(BoogieParser.java:2698)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.dat3m.dartagnan.parsers.BoogieBaseVisitor.visitLabel_or_cmd(BoogieBaseVisitor.java:170)
	at com.dat3m.dartagnan.parsers.BoogieParser$Label_or_cmdContext.accept(BoogieParser.java:2075)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitProc_decl(VisitorBoogie.java:323)
	at com.dat3m.dartagnan.parsers.program.visitors.boogie.VisitorBoogie.visitMain(VisitorBoogie.java:178)
	at com.dat3m.dartagnan.parsers.BoogieParser$MainContext.accept(BoogieParser.java:229)
	at com.dat3m.dartagnan.parsers.program.ParserBoogie.parse(ParserBoogie.java:25)
	at com.dat3m.dartagnan.parsers.program.ProgramParser.parse(ProgramParser.java:22)
	at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:47)

My LLVM & Clang is 10.0.1, Operating system is Archlinux 5.10.14.

command for this file is:
java -jar svcomp-2.0.7-jar-with-dependencies.jar -cat svcomp.cat -property ./properties/unreach-call.prp -unroll 2 -i ./benchmark_i/pthread-wmm/safe029_tso.opt_true-unreach-call.i -incrementalSolver 

dependencies:
smack 2.6.3
maven 3.6.3

I saw "__VERIFIER_nondet_X"  has been implemented in Dartagnan, I don't know why this error occurred.
And I download the competition version from SV-COMP 2021, this exception is still here.
I wonder if can give me some advice. Thx.

**Comment by hernanponcedeleon** [comment]
Can you please attach here (you might need to zip the files) the following two things:
a) the C file safe029_tso.opt_true-unreach-call.i (based on the name, you are using a quite old version of the benchmarks)
b) in Dat3M/output there should be a file called safe029_tso.opt_true-unreach-call-O).bpl

**Comment by fanhy2114** [comment]
[safe029_tso.opt_true-unreach-call.zip](https://github.com/hernanponcedeleon/Dat3M/files/5958677/safe029_tso.opt_true-unreach-call.zip)

Thanks for your reply. This benchmark is from SVCOMP 2019.
Boogie version is 2.8.26.0 and Corral is 1.0.17.0.

**Comment by hernanponcedeleon** [comment]
The problem is that the C file make use of `__VERIFIER_nondet_pointer()` for which we don't have an implementation in Dartagnan. As far as I know, these specific functions are not used in the SVCOMP benchmarks anymore. If you use the [newest version](https://github.com/sosy-lab/sv-benchmarks/blob/ea1398e79d2b8787b01967538446198d5e76b533/c/pthread-wmm/safe029_tso.opt.i) of the benchmark, it should work.

**Comment by fanhy2114** [comment]
You are right. `__VERIFIER_nondet_pointer()` is replaced with '__VERIFIER_nondet_bool()'.
Dartagnan works well in the latest SV-COMP benchmarks. Thx.
