### ISSUE TITLE
Null pointer exception in SymmetryEncoder

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#376]
I get the following null exception when running the attached bpl file with option `--encoding.symmetry.breakOn=rf`

```
[24.01.2023] 17:02:02 [ERROR] Dartagnan.main - null
java.lang.NullPointerException: null
        at com.dat3m.dartagnan.encoding.SymmetryEncoder.encodeFullSymmetryBreaking(SymmetryEncoder.java:104) ~[dartagnan-3.1.1.jar:?]
        at com.dat3m.dartagnan.verification.solving.RefinementSolver.run(RefinementSolver.java:136) ~[dartagnan-3.1.1.jar:?]
        at com.dat3m.dartagnan.verification.solving.RefinementSolver.run(RefinementSolver.java:87) ~[dartagnan-3.1.1.jar:?]
        at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:159) [dartagnan-3.1.1.jar:?]
```
[client-code-opt.zip](https://github.com/hernanponcedeleon/Dat3M/files/10491821/client-code-opt.zip)

**Comment by ThomasHaas** [comment]
Is the exception specific to this code or is it reproducible in other cases as well?

**Comment by ThomasHaas** [comment]
Symmetry breaking is totally broken right now, at least if run with relations as breaking target (`_cf` should still work).

**Comment by hernanponcedeleon** [comment]
I haven't tested in other code than this. But this is qspinlock using the same setting we always used in the cna-verification scripts. Last time I run the whole experiments we were using commit cd63a2e5e1f9be4fc3db16857cc1bbda233d8e5e and it worked, so the bug was introduced after that commit.

**Comment by ThomasHaas** [comment]
Since the WMM restructuring PR, the symmetry breaking is broken
