### ISSUE TITLE
Null Pointer in Refinement

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#59]
Refinement returns the following null pointer for mutex-4 with bound 2
```
Exception in thread "main" java.lang.NullPointerException
	at com.dat3m.dartagnan.analysis.graphRefinement.searchTree.SearchNode.replaceBy(SearchNode.java:35)
	at com.dat3m.dartagnan.analysis.graphRefinement.resolution.TreeResolution.removeUnproductiveNodes(TreeResolution.java:111)
	at com.dat3m.dartagnan.analysis.graphRefinement.resolution.TreeResolution.reduceTree(TreeResolution.java:83)
	at com.dat3m.dartagnan.analysis.graphRefinement.resolution.TreeResolution.computeViolations(TreeResolution.java:23)
	at com.dat3m.dartagnan.analysis.graphRefinement.GraphRefinement.computeResolventsFromTree(GraphRefinement.java:132)
	at com.dat3m.dartagnan.analysis.graphRefinement.GraphRefinement.kSearch(GraphRefinement.java:107)
	at com.dat3m.dartagnan.analysis.Refinement.refinementCore(Refinement.java:157)
	at com.dat3m.dartagnan.analysis.Refinement.runAnalysisGraphRefinement(Refinement.java:82)
	at com.dat3m.dartagnan.Dartagnan.selectAndRunAnalysis(Dartagnan.java:125)
	at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:92)
```

**Comment by hernanponcedeleon** [comment]
Fixed by 35cabdf4dacb42ca71e2d5e7f99e52013608c2ee
